<a href="https://colab.research.google.com/github/Yerlis09/Yerlys_CastellarJulio_KC/blob/main/taller_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nombre: ***Yerlys María Castellar Julio***

---


In [2]:
import numpy as np
import time

**Taller 1**
	
  

1.  Tienen el siguiente arreglo : 

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Como es posible obtener el siguiente resultado:
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])




**Primera Alternativa**

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8,9]) 
arr1 = (np.delete(arr,(1,3,5,7,9)))
indices = [1,2,3,4,5]
print(np.insert(arr1,(indices),-1))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Segunda Alternativa**

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
indices = [1,3,5,7,9]
arr.put(indices,-1)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Tercera Alternativa**

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
indices = [1,3,5,7,9]
arr[indices] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]




2. 	Tienen el siguiente input: np.arange(10)
Como se puede hacer para obtener el siguiente resultado:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])


In [ ]:
arr = np.arange(10).reshape((2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


3.	Con base en el siguiente input:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Obtener el siguiente resultado
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])



In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate((a,b), axis=0))


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


4.	Con base en el siguiente input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Obtener el siguiente output
array([2, 4])


**Primera Alternativa**

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
array=([a[1],b[5]])
print(array)

[2, 4]


**Segunda Alternativa**

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


**Tercera Alternativa**

In [6]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=a[a==b]
print(c) #imprime los números que son iguales

c=list(set(c)) #aqui agrupa y los pone en una lista
print(c) #aqui se imprime

[2 2 4 4]
[2, 4]


5.	Del siguiente input:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
Obtener el siguiente output
array([1,2,3,4])



**Primera Alternativa**

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.concatenate((a,b))
indice = [0,1,2,3]
print(c[indice])

[1 2 3 4]


**Segunda Alternativa**

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.concatenate((a,b))
print(c[0:4])

[1 2 3 4]


6.	Con el siguiente input:
a = np.array([2, 6, 1, 9, 10, 3, 27])
Obtener:
(array([6, 9, 10]),)


In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27]) 
indices=[1,3,4]
print(a[indices])


[ 6  9 10]


7.	Invertir las filas de un arreglo de matriz 2D
arr = np.arange(9).reshape(3,3)
Output deseado:
array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])


In [ ]:
arr = np.arange(9).reshape(3,3) 
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])